// Generated by `npm run supabase -- gen types typescript --linked`.
// Do NOT edit by hand. Re-run `scripts/sync-shared.ps1` to regenerate.
//
// Snapshot 2026-05-10: assistance catalog + service_request_records.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      admin_active_sessions: {
        Row: {
          created_at: string
          email: string | null
          last_seen: string
          session_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          last_seen?: string
          session_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          email?: string | null
          last_seen?: string
          session_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      admin_notification: {
        Row: {
          admin_user_id: string
          audit_log_id: string
          created_at: string
          id: string
          is_read: boolean
          request_id: string
          request_table: string
          updated_at: string
        }
        Insert: {
          admin_user_id: string
          audit_log_id: string
          created_at?: string
          id?: string
          is_read?: boolean
          request_id: string
          request_table: string
          updated_at?: string
        }
        Update: {
          admin_user_id?: string
          audit_log_id?: string
          created_at?: string
          id?: string
          is_read?: boolean
          request_id?: string
          request_table?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_notification_admin_user_id_fkey"
            columns: ["admin_user_id"]
            isOneToOne: false
            referencedRelation: "admins"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "admin_notification_audit_log_id_fkey"
            columns: ["audit_log_id"]
            isOneToOne: false
            referencedRelation: "audit_logs"
            referencedColumns: ["id"]
          },
        ]
      }
      admins: {
        Row: {
          category_id: string | null
          created_at: string
          is_super_admin: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          category_id?: string | null
          created_at?: string
          is_super_admin?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          category_id?: string | null
          created_at?: string
          is_super_admin?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      assistance_categories: {
        Row: {
          active: boolean
          assistance_name: string
          created_at: string
          description: string | null
          id: string
          slug: string
          sort_order: number
          theme_json: string
          updated_at: string
        }
        Insert: {
          active?: boolean
          assistance_name: string
          created_at?: string
          description?: string | null
          id?: string
          slug: string
          sort_order?: number
          theme_json?: string
          updated_at?: string
        }
        Update: {
          active?: boolean
          assistance_name?: string
          created_at?: string
          description?: string | null
          id?: string
          slug?: string
          sort_order?: number
          theme_json?: string
          updated_at?: string
        }
        Relationships: []
      }
      assistance_requirement_tips: {
        Row: {
          created_at: string
          description: string
          id: string
          requirement_id: string
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string
          id?: string
          requirement_id: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          id?: string
          requirement_id?: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assistance_requirement_tips_requirement_id_fkey"
            columns: ["requirement_id"]
            isOneToOne: false
            referencedRelation: "assistance_requirements"
            referencedColumns: ["id"]
          },
        ]
      }
      assistance_requirements: {
        Row: {
          created_at: string
          help: string | null
          id: string
          metadata: Json
          required: boolean
          service_id: string
          slot_key: string
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          help?: string | null
          id?: string
          metadata?: Json
          required?: boolean
          service_id: string
          slot_key: string
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          help?: string | null
          id?: string
          metadata?: Json
          required?: boolean
          service_id?: string
          slot_key?: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assistance_requirements_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "assistance_services"
            referencedColumns: ["id"]
          },
        ]
      }
      assistance_services: {
        Row: {
          about_html: string
          active: boolean
          attachment_slot_map: Json
          category_id: string
          created_at: string
          description_html: string
          radio_selection: Json | null
          display_name: string
          has_details_step: boolean
          id: string
          mobile_image_url: string | null
          reminder_text: string
          request_code_token: string | null
          sort_order: number
          updated_at: string
          web_intro_html: string | null
          who_bullets: Json
        }
        Insert: {
          about_html?: string
          active?: boolean
          attachment_slot_map?: Json
          category_id: string
          created_at?: string
          description_html?: string
          radio_selection?: Json | null
          display_name: string
          has_details_step?: boolean
          id?: string
          mobile_image_url?: string | null
          reminder_text?: string
          request_code_token?: string | null
          sort_order?: number
          updated_at?: string
          web_intro_html?: string | null
          who_bullets?: Json
        }
        Update: {
          about_html?: string
          active?: boolean
          attachment_slot_map?: Json
          category_id?: string
          created_at?: string
          description_html?: string
          radio_selection?: Json | null
          display_name?: string
          has_details_step?: boolean
          id?: string
          mobile_image_url?: string | null
          reminder_text?: string
          request_code_token?: string | null
          sort_order?: number
          updated_at?: string
          web_intro_html?: string | null
          who_bullets?: Json
        }
        Relationships: [
          {
            foreignKeyName: "assistance_services_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "assistance_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      assistance_requests: {
        Row: {
          additional_info: string | null
          case_study_date: string | null
          created_at: string
          financial_request_type: string | null
          id: string
          payload: Json
          payload_version: number
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          additional_info?: string | null
          case_study_date?: string | null
          created_at?: string
          financial_request_type?: string | null
          id?: string
          payload?: Json
          payload_version?: number
          request_code?: string | null
          service_id: string
          status?: string
          submitted_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          additional_info?: string | null
          case_study_date?: string | null
          created_at?: string
          financial_request_type?: string | null
          id?: string
          payload?: Json
          payload_version?: number
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "assistance_requests_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "assistance_services"
            referencedColumns: ["id"]
          },
        ]
      }
      barangays: {
        Row: {
          id: string
          name: string
        }
        Insert: {
          id?: string
          name: string
        }
        Update: {
          id?: string
          name?: string
        }
        Relationships: []
      }
      registered_voters: {
        Row: {
          age: number
          barangay_id: string
          birth_date: string
          created_at: string
          first_name: string
          id: string
          last_name: string
          middle_name: string
          sex: string
          suffix: string
          updated_at: string
          voter_id: string
        }
        Insert: {
          age: number
          barangay_id: string
          birth_date: string
          created_at?: string
          first_name: string
          id?: string
          last_name: string
          middle_name?: string
          sex: string
          suffix?: string
          updated_at?: string
          voter_id: string
        }
        Update: {
          age?: number
          barangay_id?: string
          birth_date?: string
          created_at?: string
          first_name?: string
          id?: string
          last_name?: string
          middle_name?: string
          sex?: string
          suffix?: string
          updated_at?: string
          voter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "registered_voters_barangay_id_fkey"
            columns: ["barangay_id"]
            isOneToOne: false
            referencedRelation: "barangays"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          changed_at: string
          changed_by: string | null
          id: string
          new_status: string | null
          old_status: string | null
          request_id: string
        }
        Insert: {
          action: string
          changed_at?: string
          changed_by?: string | null
          id?: string
          new_status?: string | null
          old_status?: string | null
          request_id: string
        }
        Update: {
          action?: string
          changed_at?: string
          changed_by?: string | null
          id?: string
          new_status?: string | null
          old_status?: string | null
          request_id?: string
        }
        Relationships: []
      }
      burial_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          case_study_date: string | null
          coverage: string | null
          created_at: string | null
          death_cert_file: string | null
          id: string
          indigency_cert_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          valid_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          coverage?: string | null
          created_at?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          valid_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          coverage?: string | null
          created_at?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          valid_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_burial_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_burial_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_burial_requests_death_cert_file_ra_uid"
            columns: ["death_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_burial_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_burial_requests_valid_id_file_ra_uid"
            columns: ["valid_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      columbarium_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          case_study_date: string | null
          created_at: string | null
          cremation_cert_file: string | null
          death_cert_file: string | null
          id: string
          indigency_cert_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          valid_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          cremation_cert_file?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          valid_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          cremation_cert_file?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          valid_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_columbarium_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_columbarium_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_columbarium_requests_cremation_cert_file_ra_uid"
            columns: ["cremation_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_columbarium_requests_death_cert_file_ra_uid"
            columns: ["death_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_columbarium_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_columbarium_requests_valid_id_file_ra_uid"
            columns: ["valid_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      cremation_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          case_study_date: string | null
          coverage: string | null
          created_at: string | null
          death_cert_file: string | null
          id: string
          indigency_cert_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          valid_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          coverage?: string | null
          created_at?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          valid_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          coverage?: string | null
          created_at?: string | null
          death_cert_file?: string | null
          id?: string
          indigency_cert_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          valid_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_cremation_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_cremation_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_cremation_requests_death_cert_file_ra_uid"
            columns: ["death_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_cremation_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_cremation_requests_valid_id_file_ra_uid"
            columns: ["valid_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      financial_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          case_study_date: string | null
          created_at: string | null
          financial_request_type: string | null
          id: string
          indigency_cert_file: string | null
          letter_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          valid_id_file: string | null
          voter_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          financial_request_type?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          valid_id_file?: string | null
          voter_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          financial_request_type?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          valid_id_file?: string | null
          voter_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_financial_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_financial_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_financial_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_financial_requests_letter_file_ra_uid"
            columns: ["letter_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_financial_requests_valid_id_file_ra_uid"
            columns: ["valid_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_financial_requests_voter_id_file_ra_uid"
            columns: ["voter_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      hospitalization_requests: {
        Row: {
          abstract_file: string | null
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          bill_file: string | null
          birth_cert_file: string | null
          case_study_date: string | null
          created_at: string | null
          id: string
          indigency_cert_file: string | null
          letter_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          voter_id_file: string | null
        }
        Insert: {
          abstract_file?: string | null
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          bill_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          voter_id_file?: string | null
        }
        Update: {
          abstract_file?: string | null
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          bill_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          voter_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_hospitalization_requests_abstract_file_ra_uid"
            columns: ["abstract_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_bill_file_ra_uid"
            columns: ["bill_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_birth_cert_file_ra_uid"
            columns: ["birth_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_letter_file_ra_uid"
            columns: ["letter_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_hospitalization_requests_voter_id_file_ra_uid"
            columns: ["voter_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      medical_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          birth_cert_file: string | null
          case_study_date: string | null
          created_at: string | null
          id: string
          indigency_cert_file: string | null
          letter_file: string | null
          med_cert_file: string | null
          prescription_file: string | null
          quotation_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          voter_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          med_cert_file?: string | null
          prescription_file?: string | null
          quotation_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          voter_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          med_cert_file?: string | null
          prescription_file?: string | null
          quotation_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          voter_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_medical_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_birth_cert_file_ra_uid"
            columns: ["birth_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_letter_file_ra_uid"
            columns: ["letter_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_med_cert_file_ra_uid"
            columns: ["med_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_prescription_file_ra_uid"
            columns: ["prescription_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_quotation_file_ra_uid"
            columns: ["quotation_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_medical_requests_voter_id_file_ra_uid"
            columns: ["voter_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      monetary_requests: {
        Row: {
          additional_attachment_file: string | null
          additional_info: string | null
          barangay_endorsement_file: string | null
          case_study_date: string | null
          created_at: string | null
          id: string
          indigency_cert_file: string | null
          letter_file: string | null
          request_code: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          valid_id_or_birth_cert_file: string | null
          voters_id_or_cert_file: string | null
        }
        Insert: {
          additional_attachment_file?: string | null
          additional_info?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          valid_id_or_birth_cert_file?: string | null
          voters_id_or_cert_file?: string | null
        }
        Update: {
          additional_attachment_file?: string | null
          additional_info?: string | null
          barangay_endorsement_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          letter_file?: string | null
          request_code?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          valid_id_or_birth_cert_file?: string | null
          voters_id_or_cert_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_monetary_requests_additional_attachment_file_ra_uid"
            columns: ["additional_attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_monetary_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_monetary_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_monetary_requests_letter_file_ra_uid"
            columns: ["letter_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_monetary_requests_valid_id_or_birth_cert_file_ra_uid"
            columns: ["valid_id_or_birth_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_monetary_requests_voters_id_or_cert_file_ra_uid"
            columns: ["voters_id_or_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      request_attachments: {
        Row: {
          additional_reason: string | null
          assistance_request_id: string
          created: string
          file_type: string
          path: string
          reason_for_action: string | null
          status: string
          uid: string
          updated: string
        }
        Insert: {
          additional_reason?: string | null
          assistance_request_id: string
          created?: string
          file_type: string
          path: string
          reason_for_action?: string | null
          status?: string
          uid?: string
          updated?: string
        }
        Update: {
          additional_reason?: string | null
          assistance_request_id?: string
          created?: string
          file_type?: string
          path?: string
          reason_for_action?: string | null
          status?: string
          uid?: string
          updated?: string
        }
        Relationships: []
      }
      service_request_records: {
        Row: {
          additional_info: string | null
          case_study_date: string | null
          financial_request_type: string | null
          id: string
          legacy_created_at: string | null
          legacy_request_id: string
          legacy_request_table: string
          legacy_service_id: string | null
          legacy_updated_at: string | null
          request_code: string | null
          service_key: string
          status: string | null
          submitted_at: string | null
          synced_at: string
          user_id: string
        }
        Insert: {
          additional_info?: string | null
          case_study_date?: string | null
          financial_request_type?: string | null
          id?: string
          legacy_created_at?: string | null
          legacy_request_id: string
          legacy_request_table: string
          legacy_service_id?: string | null
          legacy_updated_at?: string | null
          request_code?: string | null
          service_key: string
          status?: string | null
          submitted_at?: string | null
          synced_at?: string
          user_id: string
        }
        Update: {
          additional_info?: string | null
          case_study_date?: string | null
          financial_request_type?: string | null
          id?: string
          legacy_created_at?: string | null
          legacy_request_id?: string
          legacy_request_table?: string
          legacy_service_id?: string | null
          legacy_updated_at?: string | null
          request_code?: string | null
          service_key?: string
          status?: string | null
          submitted_at?: string | null
          synced_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_request_records_service_key_fkey"
            columns: ["service_key"]
            isOneToOne: false
            referencedRelation: "assistance_services"
            referencedColumns: ["service_key"]
          },
        ]
      }
      treatment_requests: {
        Row: {
          additional_info: string | null
          attachment_file: string | null
          barangay_endorsement_file: string | null
          birth_cert_file: string | null
          case_study_date: string | null
          created_at: string | null
          id: string
          indigency_cert_file: string | null
          lab_file: string | null
          letter_file: string | null
          med_cert_file: string | null
          request_code: string | null
          rx_file: string | null
          service_id: string
          status: string
          submitted_at: string | null
          updated_at: string | null
          user_id: string
          voter_id_file: string | null
        }
        Insert: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          lab_file?: string | null
          letter_file?: string | null
          med_cert_file?: string | null
          request_code?: string | null
          rx_file?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id: string
          voter_id_file?: string | null
        }
        Update: {
          additional_info?: string | null
          attachment_file?: string | null
          barangay_endorsement_file?: string | null
          birth_cert_file?: string | null
          case_study_date?: string | null
          created_at?: string | null
          id?: string
          indigency_cert_file?: string | null
          lab_file?: string | null
          letter_file?: string | null
          med_cert_file?: string | null
          request_code?: string | null
          rx_file?: string | null
          service_id?: string
          status?: string
          submitted_at?: string | null
          updated_at?: string | null
          user_id?: string
          voter_id_file?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_treatment_requests_attachment_file_ra_uid"
            columns: ["attachment_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_barangay_endorsement_file_ra_uid"
            columns: ["barangay_endorsement_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_birth_cert_file_ra_uid"
            columns: ["birth_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_indigency_cert_file_ra_uid"
            columns: ["indigency_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_lab_file_ra_uid"
            columns: ["lab_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_letter_file_ra_uid"
            columns: ["letter_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_med_cert_file_ra_uid"
            columns: ["med_cert_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_rx_file_ra_uid"
            columns: ["rx_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
          {
            foreignKeyName: "fk_treatment_requests_voter_id_file_ra_uid"
            columns: ["voter_id_file"]
            isOneToOne: false
            referencedRelation: "request_attachments"
            referencedColumns: ["uid"]
          },
        ]
      }
      user_notification: {
        Row: {
          action: string | null
          audit_log_id: string | null
          created_at: string
          id: string
          is_read: boolean
          new_status: string | null
          old_status: string | null
          request_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          action?: string | null
          audit_log_id?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          new_status?: string | null
          old_status?: string | null
          request_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          action?: string | null
          audit_log_id?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          new_status?: string | null
          old_status?: string | null
          request_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_notification_audit_log_id_fkey"
            columns: ["audit_log_id"]
            isOneToOne: false
            referencedRelation: "audit_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_notification_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "assistance_requests"
            referencedColumns: ["id"]
          },
        ]
      }
      user_push_token: {
        Row: {
          created_at: string
          device_id: string | null
          enabled: boolean
          id: string
          platform: string | null
          token: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          device_id?: string | null
          enabled?: boolean
          id?: string
          platform?: string | null
          token: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          device_id?: string | null
          enabled?: boolean
          id?: string
          platform?: string | null
          token?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      users: {
        Row: {
          address: string | null
          avatar_url: string | null
          birth_date: string | null
          contact_number: string
          created_at: string | null
          email: string
          first_name: string
          id: string
          last_name: string
          middle_name: string | null
          registered_voter_id: string | null
          sex: string | null
          suffix: string | null
          verified: boolean | null
          voter_id_number: string | null
        }
        Insert: {
          address?: string | null
          avatar_url?: string | null
          birth_date?: string | null
          contact_number: string
          created_at?: string | null
          email: string
          first_name: string
          id?: string
          last_name: string
          middle_name?: string | null
          registered_voter_id?: string | null
          sex?: string | null
          suffix?: string | null
          verified?: boolean | null
          voter_id_number?: string | null
        }
        Update: {
          address?: string | null
          avatar_url?: string | null
          birth_date?: string | null
          contact_number?: string
          created_at?: string | null
          email?: string
          first_name?: string
          id?: string
          last_name?: string
          middle_name?: string | null
          registered_voter_id?: string | null
          sex?: string | null
          suffix?: string | null
          verified?: boolean | null
          voter_id_number?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "users_registered_voter_id_fkey"
            columns: ["registered_voter_id"]
            isOneToOne: false
            referencedRelation: "registered_voters"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_request_op: {
        Args: {
          op: string
          patch?: Json
          request_id: string
          service_type: string
        }
        Returns: Json
      }
      begin_registration_attempt: { Args: { p_email: string }; Returns: string }
      can_access_request_attachment: {
        Args: { p_request_table: string; p_request_uid: string }
        Returns: boolean
      }
      can_access_request_table: {
        Args: { p_request_table: string }
        Returns: boolean
      }
      can_read_audit_log: {
        Args: { p_request_id: string; p_request_table: string }
        Returns: boolean
      }
      claim_admin_session: {
        Args: {
          p_email: string
          p_session_id: string
          p_ttl_seconds?: number
          p_user_id: string
        }
        Returns: boolean
      }
      cleanup_stale_admin_active_sessions: { Args: never; Returns: number }
      cleanup_user_notifications: {
        Args: { p_read_retention?: string; p_remove_superseded?: boolean }
        Returns: {
          deleted_expired_read: number
          deleted_orphaned: number
          deleted_superseded: number
          total_deleted: number
        }[]
      }
      current_admin_role: { Args: never; Returns: string }
      finalize_registration_profile: {
        Args: {
          p_address: string
          p_attempt_token: string
          p_birth_date: string
          p_contact_number: string
          p_email: string
          p_first_name: string
          p_last_name: string
          p_middle_name: string
          p_registered_voter_id: string
          p_sex: string
          p_suffix: string
          p_voter_id_number: string
        }
        Returns: string
      }
      verify_registered_voter_for_registration: {
        Args: {
          p_barangay_id: string
          p_birth_date: string
          p_first_name: string
          p_last_name: string
          p_middle_name: string
          p_sex: string
          p_suffix: string
        }
        Returns: Json
      }
      verify_voter_id_for_registration: {
        Args: { p_registered_voter_id: string; p_voter_id: string }
        Returns: Json
      }
      is_registration_email_available: { Args: { p_email: string }; Returns: boolean }
      format_request_code: {
        Args: { p_code: string; p_seq: number; p_ts: string }
        Returns: string
      }
      generate_burial_request_code: { Args: { p_ts?: string }; Returns: string }
      generate_columbarium_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_cremation_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_financial_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_hospitalization_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_medical_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_monetary_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      generate_request_code_for_service: {
        Args: { p_service: string; p_timestamp?: string }
        Returns: string
      }
      generate_treatment_request_code: {
        Args: { p_ts?: string }
        Returns: string
      }
      get_admin_session_by_user_id: {
        Args: { p_user_id: string }
        Returns: {
          created_at: string
          email: string
          last_seen: string
          session_id: string
          user_id: string
        }[]
      }
      get_latest_notifications_for_admin: {
        Args: { p_admin_user_id?: string }
        Returns: {
          action: string
          audit_log_id: string
          changed_at: string
          changed_by: string
          changed_by_role: string
          created_at: string
          id: string
          is_read: boolean
          new_status: string
          old_status: string
          request_id: string
          request_table: string
          updated_at: string
        }[]
      }
      get_latest_notifications_for_user: {
        Args: { p_limit?: number; p_user_id: string }
        Returns: {
          action: string
          audit_log_id: string
          created_at: string
          id: string
          is_read: boolean
          new_status: string
          old_status: string
          request_id: string
          request_table: string
        }[]
      }
      get_unread_notification_count_for_admin: {
        Args: { p_admin_user_id?: string }
        Returns: number
      }
      get_unread_notification_count_for_user: {
        Args: { p_user_id: string }
        Returns: number
      }
      is_action_required_request_status: {
        Args: { p_status: string }
        Returns: boolean
      }
      is_admin: { Args: never; Returns: boolean }
      is_admin_session_locked: {
        Args: {
          p_candidate_session_id?: string
          p_email: string
          p_ttl_seconds?: number
        }
        Returns: boolean
      }
      is_any_admin: { Args: never; Returns: boolean }
      is_burial_admin: { Args: never; Returns: boolean }
      is_financial_admin: { Args: never; Returns: boolean }
      is_in_progress_attachment_status: {
        Args: { p_status: string }
        Returns: boolean
      }
      is_in_progress_request_status: {
        Args: { p_status: string }
        Returns: boolean
      }
      is_managed_request_table: {
        Args: { p_request_table: string }
        Returns: boolean
      }
      is_medical_admin: { Args: never; Returns: boolean }
      is_resubmitted_attachment_status: {
        Args: { p_status: string }
        Returns: boolean
      }
      is_resubmitted_request_status: {
        Args: { p_status: string }
        Returns: boolean
      }
      is_superadmin: { Args: { uid: string }; Returns: boolean }
      upsert_user_push_token: {
        Args: {
          p_token: string
          p_platform?: string | null
          p_device_id?: string | null
          p_enabled?: boolean
        }
        Returns: string
      }
      disable_user_push_token: {
        Args: { p_token: string }
        Returns: number
      }
      mark_request_notifications_read: {
        Args: { p_request_id: string }
        Returns: number
      }
      mark_request_notifications_read_for_admin: {
        Args: {
          p_admin_user_id: string
          p_request_id: string
          p_request_table: string
        }
        Returns: number
      }
      mark_request_notifications_read_for_user: {
        Args: { p_request_id: string; p_user_id: string }
        Returns: number
      }
      normalize_admin_role: {
        Args: { p_role: string; p_service_type: string }
        Returns: string
      }
      normalize_financial_service_id_value: {
        Args: { p_value: string }
        Returns: string
      }
      normalize_request_table_name: {
        Args: { p_request_table: string }
        Returns: string
      }
      process_admin_notifications: { Args: never; Returns: number }
      prune_admin_active_sessions: {
        Args: { p_ttl_seconds?: number }
        Returns: undefined
      }
      release_admin_session: {
        Args: { p_session_id: string; p_user_id: string }
        Returns: boolean
      }
      touch_admin_session: {
        Args: {
          p_session_id: string
          p_ttl_seconds?: number
          p_user_id: string
        }
        Returns: boolean
      }
      validate_registration_attempt_token: {
        Args: { p_email: string; p_token: string }
        Returns: boolean
      }
    }
    Enums: {
      attachment_file_type:
        | "letter"
        | "voterId"
        | "validId"
        | "birthCert"
        | "barangay"
        | "indigency"
        | "abstract"
        | "bill"
        | "medCert"
        | "rx"
        | "lab"
        | "prescription"
        | "quotation"
        | "deathCert"
        | "cremationCert"
        | "attachment"
      attachment_status:
        | "pending"
        | "in progress"
        | "in_progress"
        | "approved"
        | "action_required"
        | "resubmitted"
      service_type_id:
        | "hospital"
        | "treatment"
        | "operations"
        | "emergency-finance"
        | "burial-money"
        | "burial-site"
        | "cremation"
        | "columbarium"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      attachment_file_type: [
        "letter",
        "voterId",
        "validId",
        "birthCert",
        "barangay",
        "indigency",
        "abstract",
        "bill",
        "medCert",
        "rx",
        "lab",
        "prescription",
        "quotation",
        "deathCert",
        "cremationCert",
        "attachment",
      ],
      attachment_status: [
        "pending",
        "in progress",
        "in_progress",
        "approved",
        "action_required",
        "resubmitted",
      ],
      service_type_id: [
        "hospital",
        "treatment",
        "operations",
        "emergency-finance",
        "burial-money",
        "burial-site",
        "cremation",
        "columbarium",
      ],
    },
  },
} as const
