<#
.SYNOPSIS
    Regenerate Supabase types and remind about ApoyoAdmin JS mirrors.

.DESCRIPTION
    1. Regenerates `AppCore/DatabaseTypes.ts` from the linked
       Supabase project via the Supabase CLI.
    2. Optionally reminds you to mirror domain constants from `AppCore/`
       into ApoyoAdmin `src/shared/domain/*.js` by hand (the script does
       not auto-copy TypeScript sources).
    3. Refuses to overwrite if ApoyoAdmin has uncommitted changes in
       the target path. Use -Force to override.

.NOTES
    Run from the ApoyoMobile repo root:

        pwsh -File scripts/sync-shared.ps1

    ApoyoAdmin keeps hand-maintained `src/shared/domain/*.js` siblings;
    this script does not translate TypeScript automatically.
#>

[CmdletBinding()]
param(
    [string]$AdminPath = (Resolve-Path "../ApoyoAdmin").Path,
    [switch]$Force,
    [switch]$SkipTypes
)

$ErrorActionPreference = "Stop"

$mobileRoot = $PSScriptRoot | Split-Path -Parent
$adminSharedDomain  = Join-Path $AdminPath "src\shared\domain"
$mobileTypesFile    = Join-Path $mobileRoot "AppCore\DatabaseTypes.ts"

Write-Host "Apoyo shared sync"
Write-Host ("  mobile root: {0}" -f $mobileRoot)
Write-Host ("  admin path : {0}" -f $AdminPath)

if (-not (Test-Path $AdminPath)) {
    Write-Error "Admin repo not found at $AdminPath. Pass -AdminPath."
}

# ---------------------------------------------------------------- types (canonical: AppCore/DatabaseTypes.ts)
if (-not $SkipTypes) {
    Write-Host "`nRegenerating AppCore/DatabaseTypes.ts from linked Supabase project..."
    $cliExe = Join-Path $mobileRoot ".tools\supabase\supabase.exe"
    if (-not (Test-Path $cliExe)) {
        $cliExe = "supabase"
    }
    $out = & $cliExe gen types typescript --linked 2>&1
    $exit = $LASTEXITCODE
    if ($exit -ne 0) {
        Write-Warning "supabase gen types failed (exit $exit). Skipping types update. Run 'supabase login' / 'supabase link' if not authenticated."
    }
    else {
        $clean = @(
            "// Generated by ``npm run supabase -- gen types typescript --linked``."
            "// Do NOT edit by hand. Re-run ``scripts/sync-shared.ps1`` to regenerate."
            "//"
            ("// Snapshot taken: {0:yyyy-MM-dd}." -f (Get-Date))
            ""
        )
        $body = $out | Where-Object { $_ -match "^(export|type|import|}|\s|//|/\*)" -or $_ -eq "" }
        if (-not $body -or $body.Count -lt 100) {
            $body = $out
        }
        ($clean + $body) | Set-Content -Encoding UTF8 $mobileTypesFile
        Write-Host ("  wrote {0}" -f $mobileTypesFile)
    }
}

# ---------------------------------------------------------------- safety
Push-Location $AdminPath
try {
    $dirty = git status --porcelain "src/shared/domain" 2>$null
}
finally {
    Pop-Location
}

if ($dirty -and -not $Force) {
    Write-Error @"
Uncommitted changes in $adminSharedDomain detected:

$dirty

Commit / stash them first, or rerun with -Force to overwrite.
"@
}

# ---------------------------------------------------------------- copy
if (-not (Test-Path $adminSharedDomain)) {
    New-Item -ItemType Directory -Path $adminSharedDomain -Force | Out-Null
}

Write-Host "`nAdmin domain mirror check (canonical TS: ApoyoMobile/AppCore/)..."

$appCoreDir = Join-Path $mobileRoot "AppCore"
$mobileFiles = Get-ChildItem $appCoreDir -File -Filter "*.ts" -ErrorAction SilentlyContinue

foreach ($f in $mobileFiles) {
    $jsName = [System.IO.Path]::ChangeExtension($f.Name, ".js")
    $jsPath = Join-Path $adminSharedDomain $jsName

    if (-not (Test-Path $jsPath)) {
        Write-Host ("  (no admin sibling) {0}" -f $f.Name)
    }
    else {
        Write-Host ("  ok      {0} (admin: {1})" -f $f.Name, $jsName)
    }
}

Write-Host "`nDone."
Write-Host "When you change mobile AppCore/*.ts constants used by admin, mirror them by hand in admin src/shared/domain/*.js."
